### ISSUE TITLE
[:bug:] Empty headers get mapped as "null"

### ISSUE THREAD

**Issue by kirstein** [Testlio/lambda-tools#46]
**Type:**
<:bug:>

**Description:**
If you have defined a HTTP header mapping for a lambda in agw and you do not provide the given HTTP header then the header will be mapped as "null". 

**Version:** 2.9.6

**Environment:**
OSX, node 4.4.3

**Steps to reproduce:**
- Create service
- Create an endpoint
- Map header Xxx
- Make a curl request to the given endpoint with Xxx header

**Expected result:**
Header should be mapped as "" (thats the way AGW does it)

**Actual result:**
"null"

**Affected features:**
- AGW header mapping

**Comment by henrinormak** [comment]
This should've been fixed by https://github.com/Testlio/lambda-tools/commit/1a551c1f00ef22718736f2dc4ca214675b632893
