### ISSUE TITLE
[:bug:] Missing context.functionName is missing when executing lambda with `lambda execute`

### ISSUE THREAD

**Issue by kirstein** [Testlio/lambda-tools#47]
**Type:**
<:bug:>

**Description:**
`context.functionName` is missing if lambda is executed with `lambda execute`

**Version:**
2.9.6

**Environment:**
OSX 10.11.4 node 4.4.3

**Steps to reproduce:**
- create a lambda `yo lambda-tools:lambda`
- execute the said lambda `lambda execute <lambda-name>`
- validate that `context.functionName` does not exist

**Expected result:**
`context.functionName` should be a string

**Actual result:**
`context.functionName === undefined`

**Affected features:**
- lambda executing

**Comment by henrinormak** [comment]
Few notes: If it is a string, then in practice it can only be a useable value when using the `lambda execute <lambda name>` form. When done with `lambda execute -f index.js` or `lambda execute` there is nothing to go by (the filename of the handler is perhaps the only thing).
