### ISSUE TITLE
microservices example doesn't deploy

### ISSUE THREAD

**Issue by berenddeboer** [Testlio/lambda-tools#56]
Using the latest version, deploy for the example fails. I tracked

The error shown in the log is:

`Error { [BadRequestException: Errors found during import: Unable to put integration on 'GET' for resource at path '/': Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression parameter specified: method.request.header.Authorization]] message: 'Errors found during import:\n\tUnable to put integration on \'GET\' for resource at path \'/\': Invalid mapping expression specified: Validation Result: warnings : [], errors : [Invalid mapping expression parameter specified: method.request.header.Authorization]', code: 'BadRequestException',`

I tracked this down to the x-amazon-apigateway-integration property in api.json, which has a requestParameters:

`"requestParameters": { "integration.request.header.Authorization": "method.request.header.Authorization" }`

If you remove  the "integration.request.header.Authorization" property, at least it deploys.

**Comment by georgmay** [comment]
Can you please attach the whole `api.json` file? Thanks!

**Comment by henrinormak** [comment]
@georgmay The full api.json is here - https://github.com/Testlio/lambda-tools/tree/master/examples/microservice/api.json

**Comment by henrinormak** [comment]
This should now be fixed (in 3.0.3).
