### ISSUE TITLE
[:new:] change the way s3 buckets are used during deployment

### ISSUE THREAD

**Issue by kirstein** [Testlio/lambda-tools#58]
**Type:**
<:new:>

**Description:**
Currently we upload every lambda to their own s3 bucket e.g. `lambdas-webhook-service-prod`.
This is great and all, but there is a limit to s3 buckets.

**Motivation:**
Since there is a limit to s3 buckets per account we should instead deploy lambdas to one bucket and just prefix them accordingly.

**Affected features:**
- deployments

**Proposed implementation:**
Instead of deploy everything in new bucket e.g. `lambdas-webhook-service-prod` lets deploy them under `lambda-tools-<something>-<something>-<something>/lambdas-webhook-service-prod`

**Comment by yoshuacas** [comment]
Hi, not sure if its related, but when I try to use the tool (setup) I receive a message explaining that the bucket is already existent in AWS.

Where can the bucket name be defined?

**Comment by mklopets** [comment]
@yoshuacas there is indeed a problem with S3 bucket naming, due to its unique constraint, and we hope to have the issue resolved soon. Will let you know via mention when it is fixed and properly configurable.

In the meanwhile, as this issue is incorrect in its premise of how the bucket naming works, I'm closing it.

**Comment by mklopets** [comment]
@yoshuacas While this current approach isn't ideal, try configuring the bucket name in your `.lambda-tools-rc.json` file like this:

```
{
    "project": {
        "name": "example-service"
    },
    "lambda": {
        "runtime": "nodejs4.3"
    },
    "aws": {
        "region": "us-east-1",
        "stage": "dev"
    },
    "tools": {
        "resources": {
            "s3Bucket": "some-unique-bucket-name"
        }
    }
}
```

The name you specified under the `s3Bucket` key will be suffixed with your chosen AWS region. For example, if you have set your region to `us-east-1` and `s3Bucket` to `some-unique-bucket-name`, lambda-tools will use the S3 bucket `some-unique-bucket-name-us-east-1`. The bucket should be created before initiating the deployment.

Note that the S3 bucket name has to be unique across *all* S3 buckets.
